Charts/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'Charts.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', 'my_charts.views.home', name='home'),
    url(r'^register/$', 'my_charts.views.register', name='register'),
    url(r'^login/$', 'django.contrib.auth.views.login', name='login'),
    url(r'^logout/$', 'django.contrib.auth.views.logout', name='logout'),
    url(r'^password_reset/$', 'django.contrib.auth.views.password_reset', name='password_reset'),
    url(r'^password_reset/done/$', 'django.contrib.auth.views.password_reset_done', name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        'django.contrib.auth.views.password_reset_confirm',
        name='password_reset_confirm'),
    url(r'^reset/done/$', 'django.contrib.auth.views.password_reset_complete', name='password_reset_complete'),
    url(r'^profile$', 'my_charts.views.profile', name='profile'),
    url(r'^dashboard/$', 'my_charts.views.dashboard', name='dashboard'),
    url(r'^charts/$', 'my_charts.views.charts', name='charts'),
    url(r'^about/$', 'my_charts.views.about', name='about'),
    url(r'^home/$', 'my_charts.views.home', name='home'),
    url(r'^signin/$', 'my_charts.views.signin', name='signin'),
    url(r'^contact/$', 'my_charts.views.contact', name='contact'),
    url(r'^contact/thankyou/', 'my_charts.views.thankyou', name='thankyou'),
    url(r'^contactme/', 'my_charts.views.contactview',name='contactme'),
    url(r'^read/', 'my_charts.views.read',name='read'),
    url(r'^list/$', 'my_charts.views.list', name='list'),
    url(r'^import_db/$', 'my_charts.views.import_db', name='import_db'),
    url(r'^hsummary/$', 'my_charts.views.hsummary', name='hsummary'),
    url(r'^fsummary/$', 'my_charts.views.fsummary', name='fsummary'),
    url(r'^nsummary/$', 'my_charts.views.nsummary', name='nsummary'),



)

my_charts/models.py
# from audioop import reverse

from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.core.exceptions import ValidationError
from django.core.validators import MinValueValidator, MaxValueValidator
from django import forms

# Create your models here.

class Country(models.Model):
    my_country = models.CharField(max_length=20)

    # def __unicode__(self):
    #      return u"Profile for user {0}".format(self.my_country)


class ZipCode(models.Model):
    zip = models.IntegerField(max_length=6)

    # def __unicode__(self):
    #      return u"Profile for user {0}".format(self.zip)


class HealthParameters(models.Model):
    bp_systolic = models.IntegerField(max_length=3, null=True, help_text="Can be blank: Ideal=120")
    bp_diastolic = models.IntegerField(max_length=3, null=True, help_text="Can be blank: Ideal=120")
    weight = models.DecimalField(max_digits=5, decimal_places=2, null='True', help_text='Can Be Bank: Units lbs')
    height = models.DecimalField(max_digits=5, decimal_places=2, null='True', help_text='Can Be Bank: Units cms')
    health_date = models.DateField(null=True, help_text='Date Created')
    health_day = models.CharField(max_length=10,null=True,help_text="Day")

    # def __unicode__(self):
    #      return u"Profile for user {0}".format(self.id)


class FitnessParameters(models.Model):
    min_light_activity = models.IntegerField(max_length=4, null=True, help_text='Can be bank: User generic Activity')
    min_sedentary_activity = models.IntegerField(max_length=4, null=True,
                                                 help_text='Can be bank: User sitting Activity')
    min_sleep_activity = models.IntegerField(max_length=4, null=True, help_text='Can be bank: User sitting Activity')
    min_awake = models.IntegerField(max_length=4, null=True, help_text='Can be bank: User Awake Activity')
    min_very_awake = models.IntegerField(max_length=4, null=True, help_text='Can be bank: User Awake Activity')
    fitness_date = models.DateField(null=True, help_text='Date Created')
    steps = models.IntegerField(null=True, max_length=5, help_text='Steps taken')
    distance = models.DecimalField(max_digits=5, decimal_places=2, null='True',
                                   help_text='Distance travelled : Units miles')
    activity_score = models.IntegerField(max_length=5, null=True, help_text='Calculated score')
    fitness_day = models.CharField(max_length=10,null=True,help_text="Day")
    # def __unicode__(self):
    #     return u"Profile for user {0}".format(self.id)


class NutritionParameters(models.Model):
    calories_in = models.IntegerField(max_length=5, null=True, help_text='Calories consumed')
    calories_burnt = models.IntegerField(max_length=5, null=True, help_text='Calories burnt')
    calories_planned_in = models.IntegerField(max_length=5, null=True, help_text='Calories planned for intake')
    calories_planned_out = models.IntegerField(max_length=5, null=True, help_text='Calories planned for burning')
    nutrition_date = models.DateField(null=True, help_text='Date Created')
    nutrition_day = models.CharField(max_length=10,null=True,help_text="Day")
    # def __unicode__(self):
    #     return u"Profile for user {0}".format(self.id)


class Picture(models.Model):
    img = models.ImageField(upload_to='user_images',
                              blank=True,
                              null=True)
    description = models.CharField(null=True, max_length=150)

class Player(AbstractUser):
    name = models.CharField(max_length=20)
    image = models.ForeignKey(Picture, related_name='image', null=True)
    street_address = models.TextField(max_length=150, null=True, help_text="Can be Blank")
    zipcode = models.ForeignKey(ZipCode, related_name='zipcode', null=True, help_text="Can be Blank")
    country = models.ForeignKey(Country, related_name='country', null=True, help_text="Can be Blank")
    health_param = models.ForeignKey(HealthParameters, related_name='health_param', null=True)
    fitness_param = models.ForeignKey(FitnessParameters, related_name='fitness_param', null=True)
    nutrition_param = models.ForeignKey(NutritionParameters, related_name='nutrition_param', null=True)
    GENDER_MALE = '1'
    GENDER_FEMALE = '2'
    GENDER = ( (GENDER_MALE, _('Male')), (GENDER_FEMALE, _('Female')), )
    age = models.IntegerField(max_length=2, verbose_name=_('Age'), blank=False, null=True, validators=[MinValueValidator(10), MaxValueValidator(100)])
    gender = models.CharField(max_length=1, choices=GENDER, default=GENDER_MALE, blank=False, null=True)
    # def __unicode__(self):
    #     return u"Profile for user {0}".format(self.id)


class EmailUserCreationForm(UserCreationForm):
    email = forms.EmailField(required=True)
    # phone_number = forms.DecimalField(max_digits=9)

    class Meta:
        model = Player
        fields = ("username", "email", "password1", "password2")

    def clean_username(self):
        # Since User.username is unique, this check is redundant,
        # but it sets a nicer error message than the ORM. See #13147.
        username = self.cleaned_data["username"]
        try:
            Player.objects.get(username=username)
        except Player.DoesNotExist:
            return username
        raise forms.ValidationError(
            self.error_messages['duplicate_username'],
            code='duplicate_username',
        )


# class MyForm(forms.Form):
# def as_p(self):
# "Returns this form rendered as HTML <p>s."
# return self._html_output(
#             normal_row = u"<p%(html_class_attr)s>%(label)s</p> %(field)s%('Username')s",
#             error_row = u'%s',
#             row_ender = '</p>',
#             help_text_html = u' <span class="helptext">%s</span>',
#             errors_on_separate_row = True)
#
# class MonthlyWeatherByCity(models.Model):
#     month = models.IntegerField()
#     boston_temp = models.DecimalField(max_digits=5, decimal_places=1)
#     houston_temp = models.DecimalField(max_digits=5, decimal_places=1)

from django import forms
from django.forms.widgets import *
# from django.core.mail import send_mail, BadHeaderError

# A simple contact form with four fields.
class ContactForm(forms.Form):
    name = forms.CharField()
    email = forms.EmailField()
    topic = forms.CharField()
    message = forms.CharField(widget=Textarea())

my_charts/forms.py
from django.forms import ModelForm
from models import *
from django import forms


# class MovieForm(ModelForm):
#     class Meta:
#         model = Movie


from django import forms

class ContactForm(forms.Form):
    name = forms.CharField()
    message = forms.CharField(widget=forms.Textarea)

    def send_email(self):
        # send email using the self.cleaned_data dictionary
        pass

class PictureForm(forms.Form):
    picture = forms.forms.FileField(
        label='Select a file',
        help_text='max. 42 megabytes'
    )

    # img = forms.ModelChoiceField(queryset=Picture.objects.all())

my_charts/templates/Dashboard.html
{% extends 'base.html' %}
{% load chartkick %}
{% load staticfiles %}

{% block content %}
    <link rel="stylesheet" href="{% static 'css/stylesheet.css' %}" type="text.css">

        <script src="http://www.google.com/jsapi"></script>

        <!-- To use Highcharts uncomment the following 2 lines and delete the previous one
        <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
        <script src="http://code.highcharts.com/highcharts.js"></script>
        -->
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
    <script src="http://code.highcharts.com/highcharts.js"></script>
    <script src="http://ankane.github.io/chartkick/chartkick.js"></script>

  <body>
    <link rel="stylesheet" href="{% static 'css/stylesheet.css' %}" type="text.css">
    <link href="{% static 'css/dashboard.css' %}" rel="stylesheet">
    <link href="{% static 'css/bootstrap-theme.min.css' %}" rel="stylesheet" type="text.css">
    <link href="{% static 'css/theme.css' %}" rel="stylesheet" type="text.css">
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
    <script src="http://code.highcharts.com/highcharts.js"></script>
    <script src="static/chartkick.js"></script>

    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
          <ul class="nav nav-sidebar">
              <img src="{{ user.image  }}" alt="{{ user.name }}" height="42" width="42" align=middle">
            <li class="active"><a href={% url "profile" %}>{{ user.name }} Profile</a></li>
              <BR>
            <li><a href={% url "hsummary" %}>Health Summary</a></li>
            <li><a href={% url "fsummary" %}>Fitness Summary</a></li>
            <li><a href={% url "nsummary" %}>Nutrition Summary</a></li>
          </ul>

          </ul>
          <ul class="nav nav-sidebar">
            <li><a href={% url "import_db" %}>Import Data</a></li>
            <li><a href={% url "import_db" %}">Export Data</a></li>
          </ul>

          <ul class="nav nav-sidebar">
            <li><a href="">Add/Delete Health Data</a></li>
            <li><a href="">Add/Delete Fitness Data</a></li>
            <li><a href="">Add/Delete Nutrition Data</a></li>

          </ul>
{#          <ul class="nav nav-sidebar">#}
{#            <li><a href="">Nav item again</a></li>#}
{#            <li><a href="">One more nav</a></li>#}
{#            <li><a href="">Another nav item</a></li>#}
{#          </ul>#}
        </div>
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
            <BR><BR>
          <h1 class="page-header">Dashboard</h1>

          <div class="row placeholders">
            <div class="col-xs-6 col-md-4 placeholder">
                 <div id="black">{% pie_chart user_activity with library={"title":{"text":"Fitness Activity"},"subtitle": {"text": "For 8/1/2014"}} %}</div>
              <h4>Fitness</h4>
              <span class="text-muted">Get in Shape</span>
            </div>
{#            <div class="col-xs-6 col-sm-3 placeholder">#}
{#              <img data-src="holder.js/200x200/auto/vine" class="img-responsive" alt="200x200" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIyMDAiIGhlaWdodD0iMjAwIj48cmVjdCB3aWR0aD0iMjAwIiBoZWlnaHQ9IjIwMCIgZmlsbD0iIzM5REJBQyIvPjx0ZXh0IHRleHQtYW5jaG9yPSJtaWRkbGUiIHg9IjEwMCIgeT0iMTAwIiBzdHlsZT0iZmlsbDojMUUyOTJDO2ZvbnQtd2VpZ2h0OmJvbGQ7Zm9udC1zaXplOjEzcHg7Zm9udC1mYW1pbHk6QXJpYWwsSGVsdmV0aWNhLHNhbnMtc2VyaWY7ZG9taW5hbnQtYmFzZWxpbmU6Y2VudHJhbCI+MjAweDIwMDwvdGV4dD48L3N2Zz4=">#}
{#              <h4>Label</h4>#}
{#              <span class="text-muted">Something else</span>#}
{#            </div>#}
            <div class="col-xs-6 col-md-4 placeholder">
{#              <img data-src="holder.js/200x200/auto/sky" class="img-responsive" alt="200x200" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIyMDAiIGhlaWdodD0iMjAwIj48cmVjdCB3aWR0aD0iMjAwIiBoZWlnaHQ9IjIwMCIgZmlsbD0iIzBEOEZEQiIvPjx0ZXh0IHRleHQtYW5jaG9yPSJtaWRkbGUiIHg9IjEwMCIgeT0iMTAwIiBzdHlsZT0iZmlsbDojZmZmO2ZvbnQtd2VpZ2h0OmJvbGQ7Zm9udC1zaXplOjEzcHg7Zm9udC1mYW1pbHk6QXJpYWwsSGVsdmV0aWNhLHNhbnMtc2VyaWY7ZG9taW5hbnQtYmFzZWxpbmU6Y2VudHJhbCI+MjAweDIwMDwvdGV4dD48L3N2Zz4=">#}
                <div id="black">{% bar_chart user_health with id='sizes' library={"title":{"text":"Health Activity"},"subtitle": {"text": "For 8/1/2014"}} %}</div>
              <h4>Health</h4>
              <span class="text-muted">Eat Better</span>
            </div>
            <div class="col-xs-6 col-md-4 placeholder">
{#              <img data-src="holder.js/200x200/auto/vine" class="img-responsive" alt="200x200" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIyMDAiIGhlaWdodD0iMjAwIj48cmVjdCB3aWR0aD0iMjAwIiBoZWlnaHQ9IjIwMCIgZmlsbD0iIzM5REJBQyIvPjx0ZXh0IHRleHQtYW5jaG9yPSJtaWRkbGUiIHg9IjEwMCIgeT0iMTAwIiBzdHlsZT0iZmlsbDojMUUyOTJDO2ZvbnQtd2VpZ2h0OmJvbGQ7Zm9udC1zaXplOjEzcHg7Zm9udC1mYW1pbHk6QXJpYWwsSGVsdmV0aWNhLHNhbnMtc2VyaWY7ZG9taW5hbnQtYmFzZWxpbmU6Y2VudHJhbCI+MjAweDIwMDwvdGV4dD48L3N2Zz4=">#}
                <div id="black">{% pie_chart user_nutrition with library={"title":{"text":"Nutrition Activity"},"subtitle": {"text": "For 8/1/2014"}}%}</div>
              <h4>Nutrition</h4>
              <span class="text-muted">Eat better</span>
            </div>
          </div>

          <h2 class="sub-header">Section title</h2>
          <div class="table-responsive">
            <table class="table table-striped">
              <thead>
                <tr>
                  <th>#</th>
                  <th>Header</th>
                  <th>Header</th>
                  <th>Header</th>
                  <th>Header</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td>1,001</td>
                  <td>Lorem</td>
                  <td>ipsum</td>
                  <td>dolor</td>
                  <td>sit</td>
                </tr>
                <tr>
                  <td>1,002</td>
                  <td>amet</td>
                  <td>consectetur</td>
                  <td>adipiscing</td>
                  <td>elit</td>
                </tr>
                <tr>
                  <td>1,003</td>
                  <td>Integer</td>
                  <td>nec</td>
                  <td>odio</td>
                  <td>Praesent</td>
                </tr>
                <tr>
                  <td>1,003</td>
                  <td>libero</td>
                  <td>Sed</td>
                  <td>cursus</td>
                  <td>ante</td>
                </tr>
                <tr>
                  <td>1,004</td>
                  <td>dapibus</td>
                  <td>diam</td>
                  <td>Sed</td>
                  <td>nisi</td>
                </tr>
                <tr>
                  <td>1,005</td>
                  <td>Nulla</td>
                  <td>quis</td>
                  <td>sem</td>
                  <td>at</td>
                </tr>
                <tr>
                  <td>1,006</td>
                  <td>nibh</td>
                  <td>elementum</td>
                  <td>imperdiet</td>
                  <td>Duis</td>
                </tr>
                <tr>
                  <td>1,007</td>
                  <td>sagittis</td>
                  <td>ipsum</td>
                  <td>Praesent</td>
                  <td>mauris</td>
                </tr>
                <tr>
                  <td>1,008</td>
                  <td>Fusce</td>
                  <td>nec</td>
                  <td>tellus</td>
                  <td>sed</td>
                </tr>
                <tr>
                  <td>1,009</td>
                  <td>augue</td>
                  <td>semper</td>
                  <td>porta</td>
                  <td>Mauris</td>
                </tr>
                <tr>
                  <td>1,010</td>
                  <td>massa</td>
                  <td>Vestibulum</td>
                  <td>lacinia</td>
                  <td>arcu</td>
                </tr>
                <tr>
                  <td>1,011</td>
                  <td>eget</td>
                  <td>nulla</td>
                  <td>Class</td>
                  <td>aptent</td>
                </tr>
                <tr>
                  <td>1,012</td>
                  <td>taciti</td>
                  <td>sociosqu</td>
                  <td>ad</td>
                  <td>litora</td>
                </tr>
                <tr>
                  <td>1,013</td>
                  <td>torquent</td>
                  <td>per</td>
                  <td>conubia</td>
                  <td>nostra</td>
                </tr>
                <tr>
                  <td>1,014</td>
                  <td>per</td>
                  <td>inceptos</td>
                  <td>himenaeos</td>
                  <td>Curabitur</td>
                </tr>
                <tr>
                  <td>1,015</td>
                  <td>sodales</td>
                  <td>ligula</td>
                  <td>in</td>
                  <td>libero</td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>

{% endblock content %}

my_charts/templates/Fitness_Summary.html
{% extends 'base.html' %}
{% load chartkick %}
{% load staticfiles %}

{% block content %}
    <link rel="stylesheet" href="{% static 'css/stylesheet.css' %}" type="text.css">

        <script src="http://www.google.com/jsapi"></script>

        <!-- To use Highcharts uncomment the following 2 lines and delete the previous one
        <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
        <script src="http://code.highcharts.com/highcharts.js"></script>
        -->
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
    <script src="http://code.highcharts.com/highcharts.js"></script>
    <script src="http://ankane.github.io/chartkick/chartkick.js"></script>

  <body>
    <link rel="stylesheet" href="{% static 'css/stylesheet.css' %}" type="text.css">
    <link href="{% static 'css/dashboard.css' %}" rel="stylesheet">
    <link href="{% static 'css/bootstrap-theme.min.css' %}" rel="stylesheet" type="text.css">
    <link href="{% static 'css/theme.css' %}" rel="stylesheet" type="text.css">
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
    <script src="http://code.highcharts.com/highcharts.js"></script>
    <script src="static/chartkick.js"></script>

    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
          <ul class="nav nav-sidebar">
              <img src="{{ user.image  }}" alt="{{ user.name }}" height="42" width="42" align=middle">
            <li class="active"><a href={% url "profile" %}>{{   user.name }} Profile</a></li>
              <BR>
            <li><a href={% url "hsummary" %}>Health Summary</a></li>
            <li><a href={% url "fsummary" %}>Fitness Summary</a></li>
            <li><a href={% url "nsummary" %}>Nutrition Summary</a></li>
          </ul>

          </ul>
          <ul class="nav nav-sidebar">
            <li><a href={% url "import_db" %}>Import Data</a></li>
            <li><a href={% url "import_db" %}>Export Data</a></li>
          </ul>

          <ul class="nav nav-sidebar" >
            <li><a href="">Add/Delete Health Data</a></li>
            <li><a href="">Add/Delete Fitness Data</a></li>
            <li><a href="">Add/Delete Nutrition Data</a></li>

          </ul>
{#          <ul class="nav nav-sidebar">#}
{#            <li><a href="">Nav item again</a></li>#}
{#            <li><a href="">One more nav</a></li>#}
{#            <li><a href="">Another nav item</a></li>#}
{#          </ul>#}
        </div>
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
            <BR><BR>
          <h2 class="page-header">Fitness Details</h2>

          <div class="row placeholders">
    <div id="black2">{% line_chart calories_ib with id='calories_ib' library={"title":{"text":"very awake vs Stepst"}} %}</div>
    <div id="black2">{% line_chart calories_pl with id='calories_pl' library={"title":{"text":"distance vs Sedantary"}} %}</div>


          </div>

          <h3 class="sub-header">More Details</h3>
          <div class="table-responsive">

          </div>
        </div>
      </div>
    </div>

{% endblock content %}

my_charts/templates/Nutrition_Summary.html
{% extends 'base.html' %}
{% load chartkick %}
{% load staticfiles %}

{% block content %}
    <link rel="stylesheet" href="{% static 'css/stylesheet.css' %}" type="text.css">

        <script src="http://www.google.com/jsapi"></script>

        <!-- To use Highcharts uncomment the following 2 lines and delete the previous one
        <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
        <script src="http://code.highcharts.com/highcharts.js"></script>
        -->
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
    <script src="http://code.highcharts.com/highcharts.js"></script>
    <script src="http://ankane.github.io/chartkick/chartkick.js"></script>

  <body>
    <link rel="stylesheet" href="{% static 'css/stylesheet.css' %}" type="text.css">
    <link href="{% static 'css/dashboard.css' %}" rel="stylesheet">
    <link href="{% static 'css/bootstrap-theme.min.css' %}" rel="stylesheet" type="text.css">
    <link href="{% static 'css/theme.css' %}" rel="stylesheet" type="text.css">
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
    <script src="http://code.highcharts.com/highcharts.js"></script>
    <script src="static/chartkick.js"></script>

    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
          <ul class="nav nav-sidebar">
              <img src="{{ user.image  }}" alt="{{ user.name }}" height="42" width="42" align=middle">
            <li class="active"><a href={% url "profile" %}>{{   user.name }} Profile</a></li>
              <BR>
            <li><a href={% url "hsummary" %}>Health Summary</a></li>
            <li><a href={% url "fsummary" %}>Fitness Summary</a></li>
            <li><a href={% url "nsummary" %}>Nutrition Summary</a></li>
          </ul>

          </ul>
          <ul class="nav nav-sidebar">
            <li><a href={% url "import_db" %}>Import Data</a></li>
            <li><a href={% url "import_db" %}>Export Data</a></li>
          </ul>

          <ul class="nav nav-sidebar" >
            <li><a href="">Add/Delete Health Data</a></li>
            <li><a href="">Add/Delete Fitness Data</a></li>
            <li><a href="">Add/Delete Nutrition Data</a></li>

          </ul>
{#          <ul class="nav nav-sidebar">#}
{#            <li><a href="">Nav item again</a></li>#}
{#            <li><a href="">One more nav</a></li>#}
{#            <li><a href="">Another nav item</a></li>#}
{#          </ul>#}
        </div>
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
            <BR><BR>
          <h2 class="page-header">Nutrition Details</h2>

          <div class="row placeholders">
    <div id="black2">{% line_chart calories_ib with id='calories_ib' library={"title":{"text":"Calories In out"}} %}</div>
    <div id="black2">{% line_chart calories_pl with id='calories_pl' library={"title":{"text":"Calories PLanned"}} %}</div>


          </div>

          <h3 class="sub-header">Section title</h3>
          <div class="table-responsive">

          </div>
        </div>
      </div>
    </div>

{% endblock content %}

my_charts/templates/contact.html
{% extends 'base.html' %}
{#{% load chartkick %}#}
{% load staticfiles %}
{% block content %}

    <BR><BR>
<p>This is the contacts page</p>



    {% endblock content %}

my_charts/templates/contactme.html
{% extends 'base.html' %}
{#{% load chartkick %}#}
{% load staticfiles %}
{% block content %}

    <BR><BR>
<p>This is the contacts page</p>
    <link  href="{% static 'css/bootstrap.min.css' %}" href="http://getbootstrap.com/dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="http://getbootstrap.com/examples/signin/signin.css" rel="stylesheet">

        <div id="contact_wrap">

        <div id="contact" class="clearfix">
            <div id="c_form">
                <br /><br />

                <form name="theform" class="form-signin" action="" method="post" id="theform">
                    {% csrf_token %}
                    <div id="name_email">

                        <label id="id_name">Name:</label>
                        <input type="text" name="name" value="" id="name" />
                        <label id="id_email">Email:</label>
                        <input type="text" name="email" value="" id="Email" />
                    </div><!-- end name_email -->
                    <div id="message">
                        <label id="id_message">Message:</label>
                        <textarea name="message" rows="8" cols="37"></textarea>

                    </div><!-- end message -->
                    <div id="submit">
                        <input type="image" src="http://path/to/submitbutton.png" onclick="YY_checkform('theform','name','#q','0','Field \'name\' is empty.','Email','#S','2','Field \'Email\' appears not to be valid.','message','2','1','Field \'message\' is empty.');return document.MM_returnValue" />
                    </div><!-- end submit -->
                    <input class="hidden" type="hidden" name="topic" value="Home : Contact Form Submission" id="subject" />
                </form>

            </div><!-- end c_form -->
        </div><!-- end contact -->

    </div><!-- end contact_wrap -->

{% endblock content %}